config/routes.rb
Rails.application.routes.draw do

  root to: 'airplanes#index'

  resources :airplanes # do
    # resources :seatings
  # end

  resources :seatings

  # get 'airplane/seating', to: 'airplanes#seating'
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :seatings
  # accepts_nested_attributes_for :seatings

  validates :name, presence: true, allow_blank: false
  validates :model, presence: true, allow_blank: false

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/seating.rb
class Seating < ApplicationRecord
  belongs_to :airplane

  validates :given_seats, presence: true, allow_blank: false
  validates :passengers, presence: true, allow_blank: false, numericality: { only_integer: true}

  validate :valid_array, :max_seats, on: :create

  def valid_array
    arr = JSON.parse(self.given_seats)
    if arr.all? { |e| e.class==Array } && arr.map(&:size).uniq.size == 1 && !(arr.flatten.chunk(&:zero?).count(&:first)> 0)
      true
    else
      errors.add(:given_seats, "Please provide a valid 2D")
    end
  rescue
    errors.add(:given_seats, "Please provide a valid 2D")
  end

  def max_seats
    arr = JSON.parse(self.given_seats)
    passengers = (self.passengers).to_i
    max_seats = (arr.map { |x| x.inject(:*)}).sum
    if passengers <= max_seats
      true
    else
      errors.add(:passengers, "Number of passengers allowed capacity should be #{max_seats}")
    end
  rescue
    errors.add(:given_seats, "Please provide correct passengers")
  end

end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :validate_2d_array_num_passengers, only: [:seating]
  before_action :set_airplane, only: %i[ show edit update destroy ]

  def seating
    if @valid_inputs
      @num_groups = @given_seats.count
      @prepared_seats = []

      @given_seats.each.with_index(1) do |x, i|
        t = x[0] * x[1]
        pg = []
        (1..t).each do |ps|
          pg << "#{i}-#{ps}"
        end
        @prepared_seats << pg.flatten.each_slice(x[0]).to_a
      end

      windw = []
      windw << @prepared_seats[0].collect { |r| r[0] } if @given_seats.first.first.to_i > 1
      windw << @prepared_seats[-1].collect { |r| r[-1] } if @given_seats.last.first.to_i > 1

      temp_aisle = []
      @prepared_seats.each do |gs|
        temp_aisle << gs.collect { |r| r[0] }
        temp_aisle << gs.collect { |r| r[-1] }
      end
      aisle = temp_aisle.uniq - windw.uniq

      set_aisle = seat_fillers(aisle, 0, "aisle")
      aisle_last_seat = set_aisle.present? ? set_aisle.values.last[0] : 0

      set_window = seat_fillers(windw, aisle_last_seat, "window")
      windw_last_seat = set_window.present? ? set_window.values.last[0] : aisle_last_seat

      middle = []
      @prepared_seats.each.with_index do |gs, i|
        pq = (1..@given_seats[i][0]).to_a[1...-1]
        if pq.size > 0
          pq.each do |rz|
            middle << gs.collect { |r| r[rz - 1] }
          end
        end
      end

      set_middle = seat_fillers(middle, windw_last_seat, "middle")

      @all_data = [*set_aisle,*set_window,*set_middle].to_h
    end
  end

  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1 or /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes or /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to airplane_url(@airplane), notice: "Airplane was successfully created." }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1 or /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to airplane_url(@airplane), notice: "Airplane was successfully updated." }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1 or /airplanes/1.json
  def destroy
    @airplane.destroy

    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: "Airplane was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def validate_2d_array_num_passengers
    flash[:alert] = []
    begin
      arr = JSON.parse(params[:seat_array])
      no_passengers = Integer(params[:no_passengers]) rescue 0
      if arr.all? { |e| e.class==Array } && arr.map(&:size).uniq.size == 1 && no_passengers > 0

        max_seats = (arr.map { |x| x.inject(:*)}).sum
        if arr.flatten.chunk(&:zero?).count(&:first)> 0
          flash[:alert] << "A 2D array should not contain any zero's"
          @valid_inputs = false
        elsif no_passengers > max_seats
          flash[:alert] << "Number of passengers allowed capacity should be #{max_seats}"
          @valid_inputs = false
        else
          @passengers_queue = no_passengers.to_i
          @given_seats = arr
          @valid_inputs = true
        end
      else
        flash[:alert] << "Please provide a valid 2D array and Number of passengers"
        @valid_inputs = false
      end
    rescue
      flash[:alert] << "Please provide a valid 2D array and Number of passengers"
      @valid_inputs = false
    end
  end

  def seat_fillers(fill, last_seat = 0, description)
    last_val = fill.map(&:length).max
    fill = fill.map { |e| e.values_at(0...last_val) }.transpose.flatten.compact
    Hash[fill.each.with_index(last_seat + 1).map { |x, i| [x, [i,"#{description}"]] }]
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_airplane
    @airplane = Airplane.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def airplane_params
    params.require(:airplane).permit(:name, :model)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/seatings_controller.rb
class SeatingsController < ApplicationController
  before_action :set_seating, only: %i[ show edit update destroy ]

  # GET /seatings or /seatings.json
  def index
    @seatings = Seating.all
  end

  # GET /seatings/1 or /seatings/1.json
  def show
  end

  # GET /seatings/new
  def new
    @seating = Seating.new
  end

  # GET /seatings/1/edit
  def edit
  end

  # POST /seatings or /seatings.json
  def create

    # @seating = Seating.new(seating_params)
    airplane = Airplane.first
    @seating = airplane.seatings.new(seating_params)

    respond_to do |format|
      if @seating.save
        # format.html { redirect_to seating_url(@seating), notice: "seating was successfully created." }
        format.html { redirect_to seatings_url, notice: "seating was successfully created." }
        format.json { render :show, status: :created, location: @seating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seatings/1 or /seatings/1.json
  def update
    respond_to do |format|
      if @seating.update(seating_params)
        format.html { redirect_to seating_url(@seating), notice: "seating was successfully updated." }
        format.json { render :show, status: :ok, location: @seating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seatings/1 or /seatings/1.json
  def destroy
    @seating.destroy

    respond_to do |format|
      format.html { redirect_to seatings_url, notice: "seating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seating
      @seating = Seating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seating_params
      params.require(:seating).permit(:given_seats, :passengers)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seatings_helper.rb
module SeatingsHelper
end

app/views/airplanes/_form.html.erb
<%= form_with(model: airplane) do |form| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
        <% airplane.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.name %></td>
        <td><%= airplane.model %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/seating.html.erb
<div class="card" style="width: 18rem;">
  <%= form_tag(airplane_seating_path, {:method => :get}) do %>
    <div class="mb-3">
      <label for="seat_array" class="form-label">Column/Rows:</label>
      <div class="form-text">A 2D array that represents the columns and rows, example:</div>
      <div class="form-text">[[3,2], [4,3], [2,3], [3,4]]</div>
      <div class="form-text">[[3,4], [4,5], [2,3], [3,4]]</div>
      <div class="form-text">[[2, 8], [3, 8]]</div>
      <div class="form-text">[[2, 8], [3, 8], [2, 8]]</div>
      <input type="text" class="form-control" id="seat_array" name="seat_array" value="<%=params[:seat_array]%>">
    </div>

    <div class="mb-3">
      <label for="no_passengers" class="form-label">Number of passengers:</label>
      <input type="text" class="form-control" id="no_passengers" name="no_passengers" value="<%=params[:no_passengers]%>">

    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>

  <% if flash.alert.any? %>
    <ul>
      <% flash.alert.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

</div>

<hr />

<% if @valid_inputs %>
  <h2 class="seats-generated">Airplane seats generated</h2>
  <div class="grid-container" style="grid-template-columns: <%= " auto" * @num_groups %>;">
    <% @prepared_seats.each do |ps| %>
      <div class="">
        <% ps.each do |seat| %>
          <div class="parent-seat">
            <% seat.each do |s| %>
              <div class="seat <%= @all_data[s][1] %>">
                <%= @all_data[s][0].to_i <= @passengers_queue ? @all_data[s][0] : ''  %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @airplane.model %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirplaneSeatingAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seatings/_form.html.erb
<%= form_with(model: seating) do |form| %>
  <% if seating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seating.errors.count, "error") %> prohibited this seating from being saved:</h2>
      <ul>
        <% seating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :given_seats %>
    <%= form.text_field :given_seats %>
  </div>
  <div class="field">
    <%= form.label :passengers %>
    <%= form.text_field :passengers %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seatings/edit.html.erb
<h1>Editing seating</h1>
<%= render 'form', seating: @seating %>
<%= link_to 'Show', @seating %> |
<%= link_to 'Back', seatings_path %>

app/views/seatings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>seatings</h1>
<table>
  <thead>
    <tr>
      <th>Given Seats</th>
      <th>Passengers</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @seatings.each do |seating| %>
      <tr>
        <td><%= seating.given_seats %></td>
        <td><%= seating.passengers %></td>
        <td><%= link_to 'Show', seating %></td>
        <td><%= link_to 'Edit', edit_seating_path(seating) %></td>
        <td><%= link_to 'Destroy', seating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New seating', new_seating_path %>

app/views/seatings/new.html.erb
<h1>New seating</h1>
<%= render 'form', seating: @seating %>
<%= link_to 'Back', seatings_path %>

app/views/seatings/seating.html.erb
<div class="card" style="width: 18rem;">
  <%= form_tag(seating_seating_path, {:method => :get}) do %>
    <div class="mb-3">
      <label for="seat_array" class="form-label">Column/Rows:</label>
      <div class="form-text">A 2D array that represents the columns and rows, example:</div>
      <div class="form-text">[[3,2], [4,3], [2,3], [3,4]]</div>
      <div class="form-text">[[3,4], [4,5], [2,3], [3,4]]</div>
      <div class="form-text">[[2, 8], [3, 8]]</div>
      <div class="form-text">[[2, 8], [3, 8], [2, 8]]</div>
      <input type="text" class="form-control" id="seat_array" name="seat_array" value="<%=params[:seat_array]%>">
    </div>
    <div class="mb-3">
      <label for="no_passengers" class="form-label">Number of passengers:</label>
      <input type="text" class="form-control" id="no_passengers" name="no_passengers" value="<%=params[:no_passengers]%>">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
  <% if flash.alert.any? %>
    <ul>
      <% flash.alert.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<hr />
<% if @valid_inputs %>
  <h2 class="seats-generated">seating seats generated</h2>
  <div class="grid-container" style="grid-template-columns: <%= " auto" * @num_groups %>;">
    <% @prepared_seats.each do |ps| %>
      <div class="">
        <% ps.each do |seat| %>
          <div class="parent-seat">
            <% seat.each do |s| %>
              <div class="seat <%= @all_data[s][1] %>">
                <%= @all_data[s][0].to_i <= @passengers_queue ? @all_data[s][0] : ''  %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/seatings/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>
<p>
  <strong>Model:</strong>
  <%= @airplane.model %>
</p>
<hr />
<% @airplane.seatings.each do |s|  %>
  <p> <%= s.given_seats %> </p>
  <p> <%= s.passengers %> </p>
<% end %>
<hr>
<div class="card" style="width: 18rem;">
  <%= form_tag(seatings_path) do %>
    <div class="mb-3">
      <label for="seat_array" class="form-label">Column/Rows:</label>
      <div class="form-text">A 2D array that represents the columns and rows, example:</div>
      <div class="form-text">[[3,2], [4,3], [2,3], [3,4]]</div>
      <div class="form-text">[[3,4], [4,5], [2,3], [3,4]]</div>
      <div class="form-text">[[2, 8], [3, 8]]</div>
      <div class="form-text">[[2, 8], [3, 8], [2, 8]]</div>
      <input type="text" class="form-control" id="seat_array" name="seat_array" value="<%=params[:seat_array]%>">
    </div>
    <div class="mb-3">
      <label for="no_passengers" class="form-label">Number of passengers:</label>
      <input type="text" class="form-control" id="no_passengers" name="no_passengers" value="<%=params[:no_passengers]%>">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</div>
<hr />
<% if @valid_inputs %>
  <h2 class="seats-generated">Airplane seats generated</h2>
  <div class="grid-container" style="grid-template-columns: <%= " auto" * @num_groups %>;">
    <% @prepared_seats.each do |ps| %>
      <div class="">
        <% ps.each do |seat| %>
          <div class="parent-seat">
            <% seat.each do |s| %>
              <div class="seat <%= @all_data[s][1] %>">
                <%= @all_data[s][0].to_i <= @passengers_queue ? @all_data[s][0] : ''  %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<hr />
<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>